- lib/acstools/satdet.py
- setup.cfg
Changed sat det order from 2 to 1, as per Ticket 8763 as suggested by Dave Borncamp.
Fixes #3 .
> Changed sat det order from 2 to 1

- acstools/__init__.py
- acstools/acs_destripe.py
- acstools/utils_subarr.py
- doc/source/conf.py
- doc/source/index.rst
- doc/source/utils_subarr.rst
> Fix acs_destripe to run in Python 3 and handle new subarrays

- acstools/__init__.py
- acstools/acs_destripe.py
- acstools/utils_calib.py
- doc/source/index.rst
- doc/source/utils_calib.rst
- doc/source/utils_subarr.rst
This is general clean up as prerequisite for #17. There is no change to results. Merging immediately to see dev regtest on Monday. Also close the FITS files properly in `acs_destripe`.
> acs_destripe clean up

- acstools/acs_destripe.py
> Fix a bug when bitmask was made backward compatible

- doc/source/calacs_hstcal.rst
resolves #25
Signed-off-by: James Noss <jnoss@stsci.edu>
> Update CALACS doc to include new CTE Gen 2 options

- acstools/satdet.py
Fix #28 . Also PEP8 clean-up.
Looks good to you, @dborncamp? I can't add you as a formal reviewer but I would like you to look at it before merge. Thanks!
> Astropy 2.0 compat for satdet

- acstools/acs2d.py
- acstools/acsccd.py
- acstools/acscte.py
- acstools/acsrej.py
- acstools/acssum.py
- acstools/calacs.py
Resolves #33
Signed-off-by: James Noss <jnoss@stsci.edu>
> Pass arbitrary options to executables

- acstools/acs2d.py
- acstools/acsccd.py
- acstools/acscte.py
- acstools/acsrej.py
- acstools/acssum.py
- acstools/calacs.py
resolves #39
Signed-off-by: James Noss <jnoss@stsci.edu>
> Add --help to docs for exe_args to print syntax

- acstools/utils_calib.py
These additions in utils_calib.py seem to catch all custom subarrays and also returns information about the number of bias columns.
> Added functionality to check for custom subarrays

- acstools/acs2d.py
- acstools/acsccd.py
- acstools/acscte.py
- acstools/acsrej.py
- acstools/acssum.py
- acstools/calacs.py
Fixes #42
Signed-off-by: James Noss <jnoss@stsci.edu>
> Raise an exception for non-zero returns from subprocess.call

- acstools/acsrej.py
- acstools/pars/acsrej.cfg
- acstools/pars/acsrej.cfgspc
Fix #50 . This is in conjunction with spacetelescope/hstcal#288 .
> ACSREJ to accept readnoise_only instead of newbias

- CODE_OF_CONDUCT.md
Add spacetelescope code of conduct to this repository.
> Add spacetelescope code of conduct to repo

- acstools/acs_destripe.py
- acstools/acs_destripe_plus.py
- acstools/utils_calib.py
- setup.cfg
> Clarify acs_destripe_plus doc and clean up code

- Jenkinsfile
- JenkinsfileRT
- README.rst
- acstools/acs2d.py
- acstools/acs_destripe.py
- acstools/acs_destripe_plus.py
- acstools/acsccd.py
- acstools/acscte.py
- acstools/acscteforwardmodel.py
- acstools/acsrej.py
- acstools/acssum.py
- acstools/tests/helpers.py
- acstools/tests/test_wfc_destripe.py
- acstools/tests/test_wfc_satdet.py
- conftest.py
- doc/Makefile
- doc/source/conf.py
- setup.cfg
- setup.py
Set up infrastructure for #69.
TODO:
Post-merge:
> TST: Initial CI setup

- .gitignore
- acstools/__init__.py
- acstools/acszpt.py
- acstools/satdet.py
- doc/rtd-pip-requirements
- doc/source/acszpt.rst
- doc/source/conf.py
- doc/source/index.rst
- setup.cfg
- setup.py
I have added a new module for `acstools` called `acszpt`, which address the need for an interface to programmatically query the [ACS Zeropoints Calculator](https://acszeropoints.stsci.edu/). The module is designed to only work with valid combinations of the ACS instruments, their filters, and observation dates. If the users query fails to meet the proper criteria, an error is raised along with messages for each input that failed.  
closes #77
> Zeropoint API

- acstools/acscteforwardmodel.py
- doc/source/acscteforwardmodel.rst
- doc/source/calacs_hstcal.rst
- doc/source/index.rst
Minor updates to the documentation. Includes documentation for SINKCORR and ACSCTEFORWARDMODEL. Closes #68
> SINKCORR and forward model doc updates

- Jenkinsfile
- JenkinsfileRT
Fix #88 
I missed a few lines in my last attempt at #85
> TST: Fix tests

- Jenkinsfile
- acstools/acs_destripe_plus.py
- setup.cfg
> TST: Change Jenkins container

- Jenkinsfile
- azure-pipelines.yml
Fix #93 
I have to merge this first before enabling Azure on the *other side*.
> Azure setup

- README.rst
> Add Azure badge

- .gitignore
- MANIFEST.in
- acstools/__init__.py
> Use pkg_resources to describe version

- .readthedocs.yml
- azure-pipelines.yml
Use RTD PR builder. Also remove doc build from Azure because it is no longer necessary.
> Use RTD PR builder

- .bandit.yaml
- .gitignore
- .readthedocs.yml
- CHANGES.rst
- Jenkinsfile
- JenkinsfileRT
- LICENSE.md
- MANIFEST.in
- acstools/__init__.py
- acstools/acs2d.py
- acstools/acs_destripe.py
- acstools/acs_destripe_plus.py
- acstools/acsccd.py
- acstools/acscte.py
- acstools/acscteforwardmodel.py
- acstools/acsphotcte.py
- acstools/acsrej.py
- acstools/acssum.py
- acstools/acszpt.py
- acstools/calacs.py
- azure-pipelines.yml
- conftest.py
- doc/rtd-pip-requirements
- doc/source/calacs_hstcal.rst
- doc/source/conf.py
- doc/source/index.rst
- pyproject.toml
- setup.cfg
- setup.py
Fix #103 
Fix #113
Address part of #115 by bumping minversion of Python to 3.6.
> MNT: Infrastructure update

- acstools/acs_destripe.py
- acstools/acs_destripe_plus.py
- acstools/acszpt.py
- acstools/satdet.py
- acstools/tests/test_wfc_destripe.py
- acstools/utils_calib.py
> MNT: Use f-string and PY3 style class

- acstools/acs_destripe.py
- acstools/acs_destripe_plus.py
- setup.cfg
Fix #123 
cc @mcara and @jdavies-st
> MNT: Use bitmask from astropy>=3.1

- setup.cfg
- setup.py
Putting in place to fulfill a requirement for automated delivery environment testing.
> Add project URLs to package metadata

- acstools/acszpt.py
- fixed minor typo in example
- removed usage of locally defined "extrapolation_date"
- added functionality to pass warnings that have been generated from ZPT tool, if any
Fixes #137
> Updated handling of extrapolated dates

- CITATION.md
- README.rst
> DOC: Add ASCL badge

- setup.cfg
Ops! I guess a bug fix release is coming up after this is merged.
> BUG: Fix broken entry points

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/labeler.yml
- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/open_actions.yml
Add templates and upgrade workflows.
> TST: Add templates and upgrade workflows

- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
This pull request is to allow skipping CI without fail.
> TST: Skip CI without fail

- .github/workflows/cancel_workflows.yml
- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
This pull request is to fix cancel workflow for PR from fork.
> TST: Fix cancel workflow for PRs

- Jenkinsfile
- acstools/acs_destripe.py
- acstools/satdet.py
> MNT: Replace deprecated dtypes in numpy 1.21

- acstools/acszpt.py
- doc/source/conf.py
- setup.cfg
update acszpt.py to work with the new AWS ACS Zeropoint Calculator's API
This pull request is to update the API module for acszpt.py to work with the 
new AWS API on API Gateway.
> updated acszpt.py

- acstools/acs_destripe.py
- acstools/acs_destripe_plus.py
- acstools/acscte.py
- acstools/acscteforwardmodel.py
- acstools/acsphotcte.py
- acstools/polarization_tools.py
- acstools/satdet.py
- doc/source/calacs.rst
- doc/source/index.rst
Fix links, grammar, remove outdated info, and improve clarity.
This pull request is to address outdated info on readthedocs.
> Update documentation 

- acstools/acsphotcte.py
This pull request is to update the photcte.py module with the updated API ID and Key for the new AWS control tower environment deployment requested by ITSD.
> updated photcte.py with new api id and key

- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/predeps_workflows.yml
- setup.cfg
This pull request is to add RC testing workflow to save time for the future. Also update existing stuff.
> TST: Add RC testing workflow and update existing

- acstools/acsphotcte.py
This pull request is to address ...
Fixes #<Issue Number>
> update ISR name and link for CTE model in use

- acstools/acscte.py
- acstools/acscteforwardmodel.py
- acstools/acsphotcte.py
- acstools/acszpt.py
- acstools/satdet.py
- doc/source/calacs.rst
- doc/source/index.rst
This pull request is to address minor updates to the docs before we do a bugfix release.
> Minor doc updates

- acstools/findsat_mrt.py
- acstools/utils_findsat_mrt.py
This pull request was part of a larger one over at #185 . Since @dvstark already approved these changes there, I am going to merge this without review with CI passes. The devdeps job will still fail but only for destriping tests.
Fixes https://github.com/spacetelescope/acstools/issues/182
> Fix MRT compatibility with astropy v6.0

- .github/workflows/ci_workflows.yml
- tox.ini
This pull request is to fix devdeps because photutils got installed after matplotlib downgraded numpy now.
> Fix devdeps

- acstools/acsphotcte.py
because the CTE webtool is offline
This pull request is to address chronic linkcheck failure.
> DOC: Remove broken link for now because the CTE webtool is offline
