defsetup.py
lib/acstools/satdet.py
setup.cfg

Was using deprecated call.
Adding in comments from @pllim.
NOTE: Replaced #5.

Fixed skimage.filters import, was deprecated

---

acstools/acs2d.py
acstools/acs_destripe.py
acstools/acs_destripe_plus.py
acstools/acsccd.py
acstools/acscte.py
acstools/acsrej.py
acstools/acssum.py
acstools/satdet.py
doc/rtd-pip-requirements
setup.py

Fixes #9.
@jhunkeler , looks much cleaner now:
```
.../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/dist.py:294:
UserWarning: The version specified ('714bc73b') is an invalid version,
this may not work as expected with newer versions of setuptools, pip, and PyPI.
Please see PEP 440 for more details.
running install
running bdist_egg
running egg_info
creating acstools.egg-info
writing requirements to acstools.egg-info/requires.txt
writing acstools.egg-info/PKG-INFO
writing top-level names to acstools.egg-info/top_level.txt
writing dependency_links to acstools.egg-info/dependency_links.txt
writing entry points to acstools.egg-info/entry_points.txt
writing manifest file 'acstools.egg-info/SOURCES.txt'
reading manifest file 'acstools.egg-info/SOURCES.txt'
reading …
```

Make some dependencies optional

---

acstools/utils_calib.py

It was done as part of #19 but that one was not merged, so this went through the crack.

Fix TypeError in Numpy 1.12 indexing

---

acstools/acs_destripe.py
acstools/acs_destripe_plus.py

Update ``acstools`` to use latest ``bitmask`` functions - see https://github.com/spacetelescope/stsci.tools/pull/29

Update acstools to the latest bitmask in stsci.tools

---

acstools/acs_destripe.py

Replace FITS "clobber" keyword with "overwrite". The new keyword was introduced in Astropy 1.3. The old one deprecated in 2.0 and will be removed in 3.0. Do not confuse this with the local "clobber" keyword in "acs_destripe", as there is no plans to deprecate *that*.
Note for future: When our minimum Astropy requirement has gone beyond 1.3 (not sure who decides that), "clobber" part of this logic can be removed altogether.

Compatibility with Astropy 2.0

---

doc/source/calacs_hstcal.rst

Fix #59 
There is also the `author_email` in `setup.cfg` but it was decided that that one is out of scope.

Replace help email with website

---

setup.py

Prevents:
```
$ twine upload dist/*
HTTPError: 400 Client Error: Invalid value for classifiers. Error: '' is not a valid choice for this field
```

Read classifiers as list, not string

---

JenkinsfileRT

...and pull ci-watson package from Astroconda instead of PyPI to consolidate dependencies.
Facilitated by spacetelescope/jenkins_shared_ci_utils#17
EDIT: Fix #71

Enable concurrent build configurations

---

acstools/__init__.py
acstools/acs2d.py
acstools/acs_destripe.py
acstools/acs_destripe_plus.py
acstools/acsccd.py
acstools/acscte.py
acstools/acscteforwardmodel.py
acstools/acsrej.py
acstools/acssum.py
acstools/acszpt.py
acstools/calacs.py
acstools/satdet.py
acstools/tests/helpers.py
acstools/utils_calib.py
doc/source/index.rst
setup.cfg
setup.py

Fix #65 . Also removed mention of PyRAF since it is only distributed in Python 2. This should be the last PR needed before the next release.

MNT: Remove PY2 support

---

Jenkinsfile
JenkinsfileRT

Fix #84 
`scikit-image` in `defaults` conda channel is incompatible with Numpy 1.16. So to get the updated version of `scikit-image` that is compatible, we have to `pip install` it instead.

TST: Fix satdet failure

---

Jenkinsfile
JenkinsfileRT
conftest.py

Maintenance of ci-watson as a conda package confers no benefit. Using the package as provided on PyPI is simpler.

Obtain ci-watson using pip rather than conda.

---

acstools/acs_destripe.py
acstools/acs_destripe_plus.py
acstools/utils_calib.py
doc/source/acs_destripe.rst
doc/source/acs_destripe_plus.rst

- After conversation with the ACS Team, the agreed upon MJD date for SM4 is 54967. This date corresponds to the EVA for ACS repair during SM4. 
This PR closes #118

Standardizes the SM4 MJD date and updates affected modules

---

acstools/acsphotcte.py

- Adds error handling to ensure the supplied MJD date occurs after SM4.
- Fixes typo in documentation where ACS ISR 2012-02 is referenced instead of ACS ISR 2015-05.

[quickfix] acsphotcte

---

conftest.py

Header won't show but at least it won't crash.

TST: Avoid error when pytest-astropy-header not installed

---

.github/workflows/ci_workflows.yml
.readthedocs.yml
doc/source/conf.py
setup.cfg

This pull request is to address warnings and remote data failures due to upstream changes. All the deprecation warnings are from upstream packages:
* `astropy`: Fixed in stable version that requires Python 3.8 or newer, so jobs using Python 3.7 won't see that fix.
* `pytest-remotedata`: astropy/pytest-remotedata#58
* `stsci.tools`: spacetelescope/stsci.tools#144

TST: Fix CI failures

---

acstools/satdet.py

This pull request is to address an error that pops up due to a newer version of scikit-image. The new version has deprecated "in_place" in favor of "out" in the skimage.morphology.remove_small_objects() function.

Update to the skimage.morphology.remove_small_objects() function in satdet.py.

---

.github/workflows/ci_workflows.yml
.github/workflows/open_actions.yml
.github/workflows/predeps_workflows.yml
.github/workflows/publish-to-pypi.yml
acstools/findsat_mrt.py
pyproject.toml
setup.cfg
tox.ini

This pull request is to see how badly things break with either Python 3.12 or NumPy 2.0.
Blocked by:
* https://github.com/scikit-image/scikit-image/issues/7149
Cannot test devdeps with `stsci.imagestats` due to:
* https://github.com/spacetelescope/stsci.imagestats/issues/24

TST: NumPy 2.0 and Python 3.12

---

doc/source/conf.py

This pull request is to ignore acspsf URL in linkcheck job because the service provider is blocking CI with Error 403.
This is a follow-up of #180 and #183 .

TST: Ignore acspsf URL in linkcheck job

---

.github/workflows/publish-to-pypi.yml

This pull request is to stop using OpenAstronomy workflow. Building simple wheel isn't that hard anyway. We can just copy paste from what I know works over at `stsynphot`.

BLD: Do not use OpenAstronomy workflow

---

acstools/findsat_mrt.py
acstools/utils_findsat_mrt.py

This PR is to add in functionality to acstools.utils_findsat_mrt.updatedq to expand the input mask to match the size of the original DQ array if necessary. This is needed if a satellite trail was identified and masked on a binned image, which is common. Users could do this manually, but it is needed frequently enough that it made sense to include. This step has also been designed to handle images with odd dimensions,(e.g., WFC3/UVIS are 2051x4096) which ensures the code is applicable to other imaging data. 
Warnings have been added into acstools.findsat_mrt.TrailFinder.rebin step to inform users if their data has odd dimensions and that rows/columns were being trimmed as needed to allow rebinning (this was happening already, but users may not have been aware). These trimmed rows/columns …

update_dq improvement in findsat_mrt

---

tox.ini

xref https://github.com/astropy/photutils/pull/1834 
And also clean up devdeps setup.

TST: Clean up devdeps, use photutils nightly wheel

---

acstools/utils_findsat_mrt.py

This pull request replaces the old interpolation method in acstools.utils_findsat_mrt.create_mrt_line_kernel from scipy.interpolate.interp2d to scipy.interpolate.RegularGridInterpolator. This request was made by Alyssa Guzman on behalf of DMD because interp2d has been deprecated and they want all packages to be compatible with the latest versions of 3rd party packages. For this update, I used scipy 1.14.1. I have tested the new interpolation method and it returns the same output as the prior method, with some slight variations, but these are very small and acceptable.

replace interp2d in utils_findsat_mrt

---

.github/workflows/ci_workflows.yml
.github/workflows/codeql-analysis.yml
.github/workflows/open_actions.yml
.github/workflows/predeps_workflows.yml
.github/workflows/publish-to-pypi.yml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed
